#
# Configuration for linux (ubuntu)
#

# Language choice
language: cpp
compiler:
  #  - clang
  - gcc

before_install:
- sudo apt-add-repository ppa:sonkun/sfml-development -y
- sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
- sudo apt-get update -qq

# Depency install
install:
  # update gcc
- sudo apt-get install -qq g++-4.8
  # lib install
  # opengl
- sudo apt-get install mesa-common-dev #opengl
  #glew
- sudo apt-get install libxrandr-dev libfreetype6-dev libglew1.5-dev    #glew
  #ffmpeg
  #for lucid ubuntu 10.02
  #- sudo apt-get install libavcodec-unstripped-52 libavdevice-unstripped-52 libavformat-unstripped-52 libavutil-unstripped-50 libpostproc-unstripped-51 libswscale-unstripped-0 ffmpeg
  # for precise ubuntu 12.04
- sudo apt-get install libav-tools ffmpeg
  #qt5
- sudo apt-get install qt5-default qttools5-dev-tools #qt 5

#after_install:

- if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
#define FFmpeg path to lib 32 and lib 64 ?

# Build
script : mkdir build && cd build/ && $CXX -v && cmake .. && make

# Choose branchs
branches:
  - master
